name: Run LogWorkHour Script

on:
  schedule:
    - cron: "0 0,6,12 * * 1-5"  # 7h, 13h, 19h giờ VN (tức 0h, 6h, 12h UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Restore Google credentials from secret
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

      - name: Run Python script
        run: python logWorkHour.py

      - name: Clean up credentials
        run: rm credentials.json
